### ISSUE TITLE
二日連続で定期バッチが落ちている

### ISSUE THREAD

**Issue by solufa** [frouriojs/create-frourio-app#197]
## Description
同じ理由で落ちたように見える
深刻な問題なら早めに修正、そうでなければ日々のエラー理由に変化がないことを確認しつつ通常のタスクとして修正

## Environment

- **Package version:**
  
  `vX.X.X`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [ ] macOS
- **Node.js version:**
  
  ``
- **npm version:**
  
  ``

**Comment by solufa** [comment]
もしかして #195 で解決してくれたのはこれ？

**Comment by LumaKernel** [comment]
いや、違います。

**Comment by LumaKernel** [comment]
ざっと調べた感じ、Sapper の `build:client` です。ほぼどのパターンでも落ちそうです。

- Sapper の typescript のボイラープレートを試してみたがこちらは問題ない
- エラーにある `@rollup/plugin-json` 入れても解決しなさそう？ ( rollup の使い方あっていないだけかも )

ということで今は公式のボイラープレートと見比べながら原因となりそうな差分を探っています。

**Comment by LumaKernel** [comment]
(失敗時の通知設定してるのに飛ばなかったのはなぜだ…?)

**Comment by solufa** [comment]
私は失敗時にメール来る
どんな設定をしたのかは記憶にない・・・

**Comment by LumaKernel** [comment]
とりあえず plugin-json は対応できそうです。直接的な原因まではわかりませんでしたが、 `index.svelte` を消すとエラー起きなくなったのでその依存周辺ぽいです。一応もうちょい調べると `import api from '~/server/api/$api'` っぽかったので、そこら辺の実装周辺の依存がパッチ上がったときに json 依存に含むようになった感じです。
ただ、json が import できる前提の npm package は多いと思うので、 plugin-json での対応でいいと思います。

**Comment by LumaKernel** [comment]
記録用

<details>
<summary><code>yarn build:client</code></summary>

```
yarn run v1.22.10
warning package.json: No license field
$ npm run generate
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1614528284804-0.31751922371893593/node but npm is using /home/luma/.fnm/node-versions/v14.15.4/installation/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> frourio-app@0.1.0 generate /home/luma/workspace/create-frourio-app/.tmp/67346-failed
> run-p generate:*

npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1614528284804-0.31751922371893593/node but npm is using /home/luma/.fnm/node-versions/v14.15.4/installation/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> frourio-app@0.1.0 generate:aspida /home/luma/workspace/create-frourio-app/.tmp/67346-failed
> aspida

npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1614528284804-0.31751922371893593/node but npm is using /home/luma/.fnm/node-versions/v14.15.4/installation/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> frourio-app@0.1.0 generate:server /home/luma/workspace/create-frourio-app/.tmp/67346-failed
> npm run generate --prefix server

npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1614528284804-0.31751922371893593/node but npm is using /home/luma/.fnm/node-versions/v14.15.4/installation/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> frourio-app-server@0.1.0 generate /home/luma/workspace/create-frourio-app/.tmp/67346-failed/server
> run-p generate:*

npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1614528284804-0.31751922371893593/node but npm is using /home/luma/.fnm/node-versions/v14.15.4/installation/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> frourio-app-server@0.1.0 generate:frourio /home/luma/workspace/create-frourio-app/.tmp/67346-failed/server
> frourio-express

$ sapper export --legacy
> Building...
'default' is imported from external module '@rollup/plugin-json' but never used

┌──────────────────────────────┐
│ built client with 2 warnings │
└──────────────────────────────┘
> @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.

> preferring built-in module 'assert' over local alternative at '/home/luma/workspace/create-frourio-app/node_modules/assert/assert.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning

   20.8 kB client.0c547e59.js
           │ src/node_modules/@sapper/app.mjs (33.9%)
           │ node_modules/svelte/internal/index.mjs (27.8%)
           │ src/node_modules/@sapper/internal/App.svelte (13.7%)
           │ src/components/Nav.svelte (7.3%)
           │ src/routes/_error.svelte (6.6%)
           │ src/routes/_layout.svelte (4.2%)
           │ src/node_modules/@sapper/internal/manifest-client.mjs (3.2%)
           │ node_modules/svelte/store/index.mjs (3.0%)
           │ src/client.ts (0.2%)
           └ src/node_modules/@sapper/internal/shared.mjs (0.0%)
     559 B inject_styles.5607aec6.js
           └ inject_styles.js
   8.17 kB index.532ac936.js
           │ src/routes/index.svelte (62.8%)
           │ server/node_modules/aspida/dist/index.js (22.7%)
           │ server/api/$api.ts (11.8%)
           │ commonjsHelpers.js (1.6%)
           │ server/node_modules/form-data/lib/browser.js (0.5%)
           │ src/utils/apiClient.ts (0.3%)
           └ src/node_modules/images/successkid.jpg (0.3%)
     770 B about.0d4052e8.js
           └ src/routes/about.svelte
   1.71 kB index.cdc6cbed.js
           └ src/routes/blog/index.svelte
   1.45 kB [slug].6d9928e7.js
           └ src/routes/blog/[slug].svelte
'default' is imported from external module '@rollup/plugin-json' but never used

┌───────────────────────────────────────┐
│ built client (legacy) with 2 warnings │
└───────────────────────────────────────┘
> @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.

> preferring built-in module 'assert' over local alternative at '/home/luma/workspace/create-frourio-app/node_modules/assert/assert.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning

   34.7 kB client.7c0c318c.js
           │ node_modules/regenerator-runtime/runtime.js (25.8%)
           │ src/node_modules/@sapper/app.mjs (25.3%)
           │ node_modules/svelte/internal/index.mjs (14.9%)
           │ src/node_modules/@sapper/internal/App.svelte (10.1%)
           │ src/components/Nav.svelte (5.8%)
           │ src/routes/_error.svelte (5.4%)
           │ src/routes/_layout.svelte (3.9%)
           │ src/node_modules/@sapper/internal/manifest-client.mjs (2.0%)
           │ node_modules/svelte/store/index.mjs (1.7%)
           │ node_modules/@babel/runtime/helpers/iterableToArrayLimit/_index.mjs (0.6%)
           │ node_modules/@babel/runtime/helpers/createClass/_index.mjs (0.6%)
           │ node_modules/@babel/runtime/helpers/unsupportedIterableToArray/_index.mjs (0.4%)
           │ node_modules/@babel/runtime/helpers/inherits/_index.mjs (0.4%)
           │ node_modules/@babel/runtime/helpers/typeof/_index.mjs (0.4%)
           │ commonjsHelpers.js (0.3%)
           │ node_modules/@babel/runtime/helpers/getPrototypeOf/_index.mjs (0.2%)
           │ node_modules/@babel/runtime/helpers/arrayLikeToArray/_index.mjs (0.2%)
           │ node_modules/@babel/runtime/helpers/nonIterableRest/_index.mjs (0.2%)
           │ node_modules/@babel/runtime/helpers/nonIterableSpread/_index.mjs (0.2%)
           │ node_modules/@babel/runtime/helpers/possibleConstructorReturn/_index.mjs (0.2%)
           │ node_modules/@babel/runtime/helpers/setPrototypeOf/_index.mjs (0.2%)
           │ node_modules/@babel/runtime/helpers/assertThisInitialized/_index.mjs (0.2%)
           │ node_modules/@babel/runtime/helpers/classCallCheck/_index.mjs (0.2%)
           │ node_modules/@babel/runtime/helpers/slicedToArray/_index.mjs (0.2%)
           │ node_modules/@babel/runtime/helpers/toConsumableArray/_index.mjs (0.2%)
           │ node_modules/@babel/runtime/helpers/iterableToArray/_index.mjs (0.1%)
           │ src/client.ts (0.1%)
           │ node_modules/@babel/runtime/helpers/arrayWithoutHoles/_index.mjs (0.1%)
           │ node_modules/@babel/runtime/helpers/arrayWithHoles/_index.mjs (0.1%)
           │ node_modules/@babel/runtime/regenerator/index.js (0.0%)
           └ src/node_modules/@sapper/internal/shared.mjs (0.0%)
     559 B inject_styles.fe622066.js
           └ inject_styles.js
    9.5 kB index.eec23eaa.js
           │ src/routes/index.svelte (71.1%)
           │ server/node_modules/aspida/dist/index.js (18.4%)
           │ server/api/$api.ts (9.4%)
           │ server/node_modules/form-data/lib/browser.js (0.6%)
           │ src/utils/apiClient.ts (0.2%)
           └ src/node_modules/images/successkid.jpg (0.2%)
   1.35 kB about.7f85dc2b.js
           └ src/routes/about.svelte
   2.39 kB index.c53ee319.js
           └ src/routes/blog/index.svelte
    2.3 kB [slug].67483731.js
           └ src/routes/blog/[slug].svelte
> @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.


[!] Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
/home/luma/workspace/create-frourio-app/.tmp/67346-failed/server/node_modules/mime-db/db.json (2:40)
1: {
2:   "application/1d-interleaved-parityfec": {
                                           ^
3:     "source": "iana"
4:   },
Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
    at error (/home/luma/workspace/create-frourio-app/.tmp/67346-failed/node_modules/rollup/dist/shared/rollup.js:5279:30)
    at Module.error (/home/luma/workspace/create-frourio-app/.tmp/67346-failed/node_modules/rollup/dist/shared/rollup.js:9996:16)
    at tryParse (/home/luma/workspace/create-frourio-app/.tmp/67346-failed/node_modules/rollup/dist/shared/rollup.js:9855:23)
    at Module.setSource (/home/luma/workspace/create-frourio-app/.tmp/67346-failed/node_modules/rollup/dist/shared/rollup.js:10303:19)
    at ModuleLoader.addModuleSource (/home/luma/workspace/create-frourio-app/.tmp/67346-failed/node_modules/rollup/dist/shared/rollup.js:18603:20)
    at async ModuleLoader.fetchModule (/home/luma/workspace/create-frourio-app/.tmp/67346-failed/node_modules/rollup/dist/shared/rollup.js:18659:9)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchStaticDependencies (/home/luma/workspace/create-frourio-app/.tmp/67346-failed/node_modules/rollup/dist/shared/rollup.js:18684:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (/home/luma/workspace/create-frourio-app/.tmp/67346-failed/node_modules/rollup/dist/shared/rollup.js:18661:9)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</details>

**Comment by solufa** [comment]
対応どうもです。
現時点でマイナーリリースします。

**Comment by solufa** [comment]
v0.27.0リリースされました、ありがとう！！！
