### ISSUE TITLE
WSL 2 で GUI が自動的に開かない

### ISSUE THREAD

**Issue by su8ru** [frouriojs/create-frourio-app#72]
## Description

WSL 2 on Windows 環境で create が異常終了します。

yarn で発覚し、npm および npx も試しましたがだめでした。

## Environment

- **Package version:**
  
  `v0.15.3`
- **OS:**
  Ubuntu 20.04 focal (on the Windows Subsystem for Linux)
  
  - [x] Linux
  - [x] Windows
  - [ ] macOS
- **Node.js version:**
  
  `v12.18.2`
- **npm version:**
  
  `v6.14.5`
- **yarn version:**
  
  `v1.22.4`

## Additional context

```
$ yarn create frourio-app demo-next-fastify
yarn create v1.22.4
[1/4] Resolving packages...
warning create-frourio-app > next > mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning create-frourio-app > next > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning create-frourio-app > next > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning create-frourio-app > next > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
[2/4] Fetching packages...
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-frourio-app@0.15.3" with binaries:
      - create-frourio-app
(node:701) UnhandledPromiseRejectionWarning: Error: Command failed: wslpath \System32\WindowsPowerShell\v1.0\powershell.exe
wslpath: \System32\WindowsPowerShell\v1.0\powershell.exe

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
(node:701) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:701) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by su8ru** [comment]
`"` で囲った上で、ドライブレターも指定すれば動く気はしますが………取得できるものなのでしょうか……？

![image](https://user-images.githubusercontent.com/33474143/96601411-f41d9400-132c-11eb-85a3-20ffbb7b946c.png)
![image](https://user-images.githubusercontent.com/33474143/96601669-38109900-132d-11eb-9c4a-9521ddcb30ab.png)

**Comment by solufa** [comment]
恐らくここが原因です
https://github.com/sindresorhus/open/blob/master/index.js#L73

対策を検討します
私のWSL2では発生しないので他にも要因がありそうです

**Comment by solufa** [comment]
根本的な解決ではないですがv0.15.4 でエラー捕捉しました
手動で開けるか確認お願いします

**Comment by solufa** [comment]
✖ node:14.13.1-stretch-slim
〇 node:latest
という情報あり

**Comment by su8ru** [comment]
Node `v14.14.0` でも変わらず。`v15.0.1` では以下のエラーとともに終了してしまいました……

```
success Installed "create-frourio-app@0.15.5" with binaries:
      - create-frourio-app
node:child_process:309
      ex = new Error('Command failed: ' + cmd + '\n' + stderr);
           ^

Error: Command failed: wslpath \System32\WindowsPowerShell\v1.0\powershell.exe
wslpath: \System32\WindowsPowerShell\v1.0\powershell.exe

    at ChildProcess.exithandler (node:child_process:309:12)
    at ChildProcess.emit (node:events:327:20)
    at maybeClose (node:internal/child_process:1048:16)
    at Socket.<anonymous> (node:internal/child_process:439:11)
    at Socket.emit (node:events:327:20)
    at Pipe.<anonymous> (node:net:656:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'wslpath \\System32\\WindowsPowerShell\\v1.0\\powershell.exe',
  stdout: '',
  stderr: 'wslpath: \\System32\\WindowsPowerShell\\v1.0\\powershell.exe\n'
}
error Command failed.
Exit code: 1
Command: /home/subaru/.yarn/bin/create-frourio-app
Arguments: aaa
Directory: /home/subaru/tmp
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

**Comment by solufa** [comment]
windows のドライブが複数あると失敗するということまでは判明

**Comment by LumaKernel** [comment]
`wslview` という便利なコマンドがあったりします。 `wslview https://github.com` など。open 側にこれを使う分岐を入れるのが割と早かったりしそう。僕の環境では WSL2 ですが open で問題なく動いています…。

https://github.com/sindresorhus/open/pull/188#issuecomment-671028351

既存の powershell での実装で実現できているいくつかのことが実現できてないとかで使っていない？

**Comment by su8ru** [comment]
あれ………（やはり私の環境が原因だったりするのでしょうか………）

```
> wslview localhost:3000
/usr/bin/wslview: line 108: "/mnt/"c/Windows/System32/reg.exe: No such file or directory
/usr/bin/wslview: line 98: "/mnt/"c/Windows/System32/chcp.com: No such file or directory
/usr/bin/wslview: line 103: "/mnt/"c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe: No such file or directory
/usr/bin/wslview: line 98: "/mnt/"c/Windows/System32/chcp.com: No such file or directory
```

`"/mnt/"c/...` が怪しいですが………
